version: '3'

networks:
  LaCaja_cotizador_bicicleta:

services:
  nginx:
    restart: unless-stopped
    image: nginx:alpine
    container_name: webserver
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - php
    networks:
      - LaCaja_cotizador_bicicleta

  php:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/php.dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "9000:9000"
    networks:
      - LaCaja_cotizador_bicicleta

  memcached:
    restart: unless-stopped
    container_name: memcached
    image: bitnami/memcached:latest
    ports:
      - "11211:11211"
    networks:
      - LaCaja_cotizador_bicicleta
volumes:
  php:
    driver: "local"
  nginx:
    driver: "local"
