// EXAMPLE: https://github.com/rmariuzzo/Lang.js/blob/master/test/fixture/messages.json
// noinspection SpellCheckingInspection
module.exports = {
    'es.cotizador': {
        'titles': {
            'personal_information': 'Datos personales',
            'insert_your_details_to_start_your_policy': 'Ingresá tus datos para comenzar a armar tu póliza.',
            'additional_personal_information': 'Datos personales adicionales',
            'contractual_address': 'Domicilio Contractual',
            'payment_method': 'Forma de Pago',
            'confirm': 'Confirmación de la Solicitud',
            'operation_center_online': 'Centro de Operaciones Online',
        },

        'subtitle': {
            'contractual_address_subtitle': 'Es el domicilio donde te llegará las notificaciones y documentación de tu seguro.',
            'select_how_to_pay_for_the_service': 'Elegí cómo pagar tu seguro',
            'you_can_select_the_option': 'Podés elegir la opción más cómoda para vos.',
            'authorize_bank_payment': 'Autorizo a que las sumas de dinero necesarias para atender al cobro de los premios del Seguro de Bicicleta y Monopatín y sus respectivas renovaciones, sean debitados en forma directa y automática de la tarjeta de crédito o cuenta bancaria indicada más arriba. Esta autorización no responsabiliza al Banco pagador de la Tarjeta sobre posibles reclamos fundados en el importe a abonar ni en la calidad de la prestación brindada por "Caja de Seguros S.A.". El cobro se realizará por mes adelantado. Me notifico que el monto de la cuota informada corresponde a un periodo regular. En el primer mes se cobrará un periodo irregular de un mes y/o fracción.',
            'personal_data': 'Datos Personales',
            'payment_method': 'Forma de Pago',
            'already_secured': '¡Ya estás asegurado!',
            'normalize_cp': 'Normalización de Código Postal',
            'car_insurance': 'Seguro de Auto',
            'house_insurance': 'Seguro de Hogar',
            'phone_insurance': 'Seguro de Tecnología Móvil',
        },

        'general': {
            'view_more': 'Ver más',
            'continue': 'Continuar',
            'tel_display': '0810 888-2888',
            'select': 'Seleccioná',
            'confirm': 'Confirmar',
            'read_more': 'Leer más',
        },

        'promotions': {
            'show_plan_promotion_text': 'Suma asegurada: :amount con franquicia del :percent%',
            'plan': 'PLAN :id',
            'your_insurance': 'Tu seguro',
            'hire': 'Contratá',
            'hire_online': 'Contratá online',
            'price_per_month': 'Por mes: $:price',
            'pay_with_card': 'Pago con Tarjetas',
            'pay_with_other_method': 'Otros medios de pago',
            'secure_site': 'Sitio 100% seguro',
            'secure_site_text': 'Tus datos están protegidos',
            'thanks_you_for_choosing_us': 'Gracias por elegirnos.',
            'access_to_your_account': 'Accedé a la documentación de tu póliza ingresando a nuestro:',
            'policy_successful_emitted': 'La póliza se emitió con éxito y la vas a recibir por email en los próximos minutos.',
            'download_our_app_long': 'Descargá nuestra App y descubrí todo lo que podes hacer desde tu celular',
            'keep_your_documentation': 'Llevá tu documentación siempre con vos, denunciá un siniestro o seguí el estado de tus trámites entre otras operaciones y no te preocupes más',
            'meet_our_app': 'Conocé nuestra App',
            'see_other_products': 'Conocé otros productos',
            'house_insurance_promotion_text': 'Empezá a disfrutar de la tranquilidad que vos y tu familia se merecen.',
            'car_insurance_promotion_text': 'Asegurá tu auto de la forma más simple y mantenete siempre en movimiento.',
            'phone_insurance_promotion_text': 'Un seguro de fácil contratación y a un precio muy conveniente.',
        },

        'form': {
            'titular_fullname': 'Nombre y Apellido Titular',
            'name': 'Nombre',
            'names': 'Nombre/s',
            'last_names': 'Apellido/s',
            'document': 'Documento',
            'number': 'Número',
            'birth_date': 'Fecha de Nacimiento',
            'email': 'Correo electrónico',
            'area_code': 'Código área',
            'phone_without_code': 'N° Celular sin 11 o 15',
            'phone': 'Teléfono',
            'gender': 'Género',
            'nationality': 'Nacionalidad',
            'street': 'Calle',
            'address': 'Domicilio',
            'address_number': 'Nro',
            'address_floor': 'Piso',
            'address_department': 'Depto',
            'postal_code': 'Código Postal',
            'locality': 'Localidad',
            'province': 'Provincia',
            'credit_card': 'Tarjeta de crédito',
            'bank_account': 'Cuenta bancaria',
            'year': 'Año',
            'month': 'Mes',
            'expiration_month': 'Mes de Vencimiento',
            'expiration_year': 'Año de Vencimiento',
            'cbu': 'CBU N°',
            'document_type': 'Tipo de documento',
            'fullname': 'Apellido y nombre',
            'contractual_address': 'Domicilio contractual',
            'type': 'Tipo',
            'debit_of_account': 'Débito en cuenta',
            'credit': 'Crédito',
            'accept_terms_and_services': 'Acepto las condiciones',
            'select_location': 'Seleccioná la localidad',
            'select_neighborhood': 'Seleccioná el barrio',
            'party': 'Partido',
            'height_from': 'Altura desde',
        },

        'terms_and_services': {
            '1': '(i) Declaro que los datos informados son correctos, exactos y revisten carácter de declaración jurada.',
            '2': '(ii) Acepto que el envío de la solicitud no otorga cobertura. Sólo habrá seguro si La Caja la acepta. De lo contrario, la solicitud quedará sin efecto.',
            '3': '(iii) Solicito que se me entregue la documentación referida a mi póliza por medios electrónicos. Autorizo a que me envíen mensajes por Whats App al teléfono celular informado y/o a través de cualquier otro medio electrónico (Ej: Mail, Chat online, App Móvil).',
            '4': '(iv) Presto conformidad para que la información que otorgo en esta solicitud sea utilizada por La Caja para acciones de marketing en forma directa o a través de terceros.'
        },
    }
}
